#######
Implementaion of Logic Gates using Perceptron

Logic Gates to implement for 3 i/p variables.

    OR
    NOT
    XOR
    XNOR
    NAND
    NOR
    AND

Perceptron model function
$$ z = \sum_{i=1}^m(w_i * x_i) +b $$

Sigmoid Function
$$ f(z) = \frac{1}{1 + e^{-z}} $$

Part 1. Write a tensorflow program to implement a perceptron using functions described above for AND , OR and NAND logic gates. Choose weights and bias values accordingly.



In [4]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[0],[0],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for AND GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.457062
iteration=  1000 cost=  0.303673
iteration=  2000 cost=  0.255684
iteration=  3000 cost=  0.223261
iteration=  4000 cost=  0.199176
iteration=  5000 cost=  0.180205
iteration=  6000 cost=  0.164696
iteration=  7000 cost=  0.151696
iteration=  8000 cost=  0.140604
iteration=  9000 cost=  0.13101
iteration=  10000 cost=  0.122621
iteration=  11000 cost=  0.115219
iteration=  12000 cost=  0.108639
Validating output for AND GATE
[[ 0.00350105]
 [ 0.11848825]
 [ 0.11607921]
 [ 0.83400267]]


# OR gate

In [3]:
import tensorflow as tf
import numpy as np

x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)


multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[1],[1],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.856719
iteration=  1000 cost=  0.329645
iteration=  2000 cost=  0.25836
iteration=  3000 cost=  0.21155
iteration=  4000 cost=  0.178319
iteration=  5000 cost=  0.15362
iteration=  6000 cost=  0.134604
iteration=  7000 cost=  0.119553
iteration=  8000 cost=  0.10737
iteration=  9000 cost=  0.0973254
iteration=  10000 cost=  0.0889155
iteration=  11000 cost=  0.0817805
iteration=  12000 cost=  0.0756579
Validating output for OR GATE
[[ 0.15912212]
 [ 0.93771648]
 [ 0.93785483]
 [ 0.9991678 ]]


# NAND gate


In [5]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[1],[1],[1],[0]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for NAND GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.666023
iteration=  1000 cost=  0.425386
iteration=  2000 cost=  0.341137
iteration=  3000 cost=  0.287012
iteration=  4000 cost=  0.24879
iteration=  5000 cost=  0.220038
iteration=  6000 cost=  0.197451
iteration=  7000 cost=  0.179147
iteration=  8000 cost=  0.163966
iteration=  9000 cost=  0.151146
iteration=  10000 cost=  0.140163
iteration=  11000 cost=  0.130642
iteration=  12000 cost=  0.122305
Validating output for NAND GATE
[[ 0.99491984]
 [ 0.86976033]
 [ 0.86947554]
 [ 0.18510209]]
